[package]
name = "styx-tree"
version = "5.0.0-rc.5"
edition.workspace = true
rust-version.workspace = true
description = "High-level syntax tree for the Styx configuration language"
license.workspace = true
repository.workspace = true

[package.metadata]

[package.metadata."docs.rs"]
rustdoc-args = ["--html-in-header", "arborium-header.html"]

[features]
default = []
facet = ["dep:facet", "styx-parse/facet"]

[dependencies]
styx-parse.workspace = true
ariadne.workspace = true
facet = { workspace = true, optional = true }
facet-testhelpers.workspace = true

[dev-dependencies]
insta.workspace = true
strip-ansi-escapes.workspace = true
facet.workspace = true
facet-json = { git = "https://github.com/facet-rs/facet", rev = "dc57e24e381f0c61b4acfa242c368656a84348d4" }
facet-postcard = { git = "https://github.com/facet-rs/facet", rev = "dc57e24e381f0c61b4acfa242c368656a84348d4" }
